### ISSUE TITLE
[Dúvida] Duvida sobre aproveitamento dos topicos.

### ISSUE THREAD

**Issue by reisguilherme** [plinioleitao/bd-2022-1-bia#410]
Por que foi dito que para conseguir aproveitamento em algum tópico era preciso atingir pelo menos 50% do esperado sendo que você sempre retira o aproveitamento caso a resposta não esteja 100% do jeito que você quer?

**Comment by plinioleitao** [comment]
Bom dia.
Se estiver incorreto, não se refere à interpretação do professor.
O prazo de 07 dias promove que o aluno possa revisar a sua resposta, visando a remover incorreções. Tal não ocorreria se a avaliação fosse aplicada presencialmente.
No próximo encontro presencial, poderei esclarecer mais.
