### ISSUE TITLE
[Dúvida] Chave estrangeira em SQL

### ISSUE THREAD

**Issue by cachops** [plinioleitao/bd-2022-1-bia#412]
Não está claro para mim qual a diferença entre as duas seguintes.

- FOREIGN KEY (Dnr) REFERENCES DEPARTAMENTO(Dnumero)
- ADD CONSTRAINT FUNCIONARIO_FK_TRABALHA_PARA
FOREIGN KEY(Dnr) REFERENCES DEPARTAMENTO(Dnumero)

Gostaria de saber qual a diferença entre as duas.

**Comment by plinioleitao** [comment]
No primeiro caso, a restrição foi potencialmente inserida via comando CREATE TABLE.
No segundo caso, a restrição foi inserida via comando ALTER TABLE.
