### ISSUE TITLE
[Dúvida] cardinalidade

### ISSUE THREAD

**Issue by cachops** [plinioleitao/bd-2022-1-bia#422]
- quando eu estiver escrevendo a cardinalidade de uma relação em que um dos lados pode ter de 0 a muitos, qual notação usar? (0,n), 0..n, 0:n.
- e depois de já ter escolhido a notação, como eu represento algo que só pode ter 1 entidade, seria (1,1)? 
- na notação que estava nos exemplos nos tópicos, n significa que pode ter de 0 a n ou de 1 a n?

**Comment by plinioleitao** [comment]
Não há escolha de notação, conforme o enunciado da questão, a notação é aquela explorada nos execícios em sala de aula.
Favor ver a notação no [Tópico 19a](https://github.com/plinioleitao/bd-2022-1-bia/blob/main/topicos/topico-19a.md).

**Comment by cachops** [comment]
o tópico que explica minha pergunta é o 15a e não o 19a, caso alguém leia isso no futuro (y)

**Comment by plinioleitao** [comment]
O [Tópico 19a](https://github.com/plinioleitao/bd-2022-1-bia/blob/main/topicos/topico-19a.md) é um exemplo da notação.

Você menciona (min, máx):
- a participação parcial denota min=0;
- a participação total denoma min=1;
- a cardinalidade 1 denota máx=1;
- a cardinalidade N denota máx=N.

Tal foi repetidas vezes explrado em sala de aula.

**Comment by cachops** [comment]
eu não preciso representar um min = 11 por exemplo?

**Comment by plinioleitao** [comment]
Sugiro que se concentre na solução das atividades dos tópicos da presente semana. Sobre a sua última pergunta, podemos esclarecer na próxima aula.

**Comment by cachops** [comment]
mas é que na atividade eu tenho um time que não pode ter menos de 11 jogadores pra entrar em campo, mas não tem número máximo de jogadores, escalados ou não para o jogo, na reserva ou não. se isso não afetar minha nota não tenho problema de ver como fazer na próxima aula, mas não sei exatamente qual critério vai ser usado para a correção!

**Comment by plinioleitao** [comment]
Realize a modelagem com os recursos explorados em sala de aula. 
Se você enxerga alguma restrição que não pode ser representada com os recursos, então não aborde essa restrição.
