### ISSUE TITLE
[Dúvida] <Tópico-20>

### ISSUE THREAD

**Issue by Fabrycio-Nakano** [plinioleitao/bd-2022-1-bia#425]
Professor boa tarde,gostaria de confirmar com o senhor o que ocorreu com a atividade do tópico 20 minha...o senhor colocou como não entregue, mas ela está aqui: https://github.com/Fabrycio-Nakano/bd-2022-1-bia/blob/main/topico-20/topico-20.jpeg

**Comment by plinioleitao** [comment]
Bom dia,

Fiz a análise do tópico indicado.

Grato,

Prof. Plinio de Sa Leitao-Junior, PhD.
Associate Professor, Institute of Informatics - INF
Federal University of Goiás - UFG - Brazil


Em sex., 9 de set. de 2022 às 17:18, Fabrycio-Nakano <
***@***.***> escreveu:

**Comment by plinioleitao** [comment]
O Tópico 20 foi analisado.
